chore: nightly build
alexa-games/skill-flow-builder pull request #21
Opened 2020-10-16 23:06 UTC by tyliec

# chore: nightly build

Adds a nightly build to our CI setup.

## Description

TravisCI will run this build nightly and publish any changes. After this is merged in, need to go on TravisCI's web panel and set up the cron job for `master`.

## Motivation and Context

Continuous testing of our builds.

## Testing

Ran test builds in a test branch.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [X] I have read the **README** document
- [ ] I have added tests to cover my changes
- [X] All new and existing tests passed

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

[issues]: https://github.com/alexa-games/skill-flow-builder/issues

2020-10-17 00:38 UTC, anfazio commented on packages/sfb-cli/README.md
> +      this.logger.status('Waving as well...');
Was this change intentional?

2020-10-17 01:21 UTC, tyliec commented on packages/sfb-cli/README.md
> +      this.logger.status('Waving as well...');
![download](https://user-images.githubusercontent.com/15609358/96325391-0f9e3d00-0fc3-11eb-9cbc-1099d1c4cb75.jpeg)

It was not, fixing now.

2020-10-19 20:08 UTC, anfazio requested changes

2020-10-19 20:08 UTC, anfazio commented on .travis.yml
> +    if: type = cron AND branch = master
Nightly builds should be based on the develop branch instead

2020-10-19 20:56 UTC, anfazio requested changes

2020-10-19 20:56 UTC, anfazio commented on packages/sfb-cli/lib/manifestUtils.ts
> +        const version = semver.coerce(toolingMetadata.version);
Let's do this as a separate PR as this change should really be going into `develop`

2020-10-19 21:22 UTC, anfazio approved these changes

2020-10-19 21:26 UTC, merged